[2016-10-22 18:33:46][NOTICE][logId:75173653][Request: { 	"interface": "fetchStock", 	"data": { 		"name": "test", 		"num": 3000 	} }]
[2016-10-22 18:33:46][DEBUG][logId:75173653][Receive params: {"name":"test","num":3000}]
[2016-10-22 18:33:46][DEBUG][logId:75173653][read config file from disk: /Users/fangshuyu/data/CommodityManagement/Configs/db.yaml]
[2016-10-22 18:33:46][ERROR][logId:75173653][PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connectors/Connector.php:119 Stack trace: #0 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connectors/Connector.php(119): PDO->__construct('mysql:host=127....', 'root', 'root', Array) #1 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connectors/Connector.php(56): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'root', 'root', Array) #2 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array) #3 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connectors/ConnectionFactory.php(100): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() #5 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connection.php(956): call_user_func(Object(Closure)) #6 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connection.php(824): Illuminate\Database\Connection->getPdo() #7 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connection.php(709): Illuminate\Database\Connection->reconnectIfMissingConnection() #8 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Connection.php(351): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) #9 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Query/Builder.php(1648): Illuminate\Database\Connection->select('select * from `...', Array, true) #10 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Query/Builder.php(1634): Illuminate\Database\Query\Builder->runSelect() #11 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Eloquent/Builder.php(613): Illuminate\Database\Query\Builder->get(Array) #12 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Eloquent/Builder.php(318): Illuminate\Database\Eloquent\Builder->getModels(Array) #13 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Eloquent/Builder.php(288): Illuminate\Database\Eloquent\Builder->get(Array) #14 /Users/fangshuyu/data/CommodityManagement/vendor/illuminate/database/Eloquent/Builder.php(301): Illuminate\Database\Eloquent\Builder->first(Array) #15 /Users/fangshuyu/data/CommodityManagement/services/CommodityManagement.php(23): Illuminate\Database\Eloquent\Builder->firstOrFail() #16 /Users/fangshuyu/data/CommodityManagement/controllers/FetchStock.php(26): Services\CommodityManagement::fetchStock('test') #17 /Users/fangshuyu/data/CommodityManagement/index.php(70): Controllers\FetchStock::todo(Array) #18 /Users/fangshuyu/data/CommodityManagement/index.php(85): Index::todo() #19 {main}]
[2016-10-22 18:33:46][NOTICE][logId:75173653][Response: {"returnCode":1045,"returnMsg":"system error","data":[]}]
[2016-10-22 18:36:00][NOTICE][logId:4431126][Request: { 	"interface": "fetchStock", 	"data": { 		"name": "test", 		"num": 3000 	} }]
[2016-10-22 18:36:00][DEBUG][logId:4431126][Receive params: {"name":"test","num":3000}]
[2016-10-22 18:36:00][DEBUG][logId:4431126][read config file from disk: /Users/fangshuyu/data/CommodityManagement/Configs/db.yaml]
[2016-10-22 18:36:00][ERROR][logId:4431126][fail to query db: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)]
[2016-10-22 18:36:00][ERROR][logId:4431126][Exception: db error in /Users/fangshuyu/data/CommodityManagement/common/Errors.php:47 Stack trace: #0 /Users/fangshuyu/data/CommodityManagement/services/CommodityManagement.php(32): Common\Errors::throws(10005) #1 /Users/fangshuyu/data/CommodityManagement/controllers/FetchStock.php(26): Services\CommodityManagement::fetchStock('test') #2 /Users/fangshuyu/data/CommodityManagement/index.php(70): Controllers\FetchStock::todo(Array) #3 /Users/fangshuyu/data/CommodityManagement/index.php(85): Index::todo() #4 {main}]
[2016-10-22 18:36:00][NOTICE][logId:4431126][Response: {"returnCode":10005,"returnMsg":"db error","data":[]}]
